-- Run this in the SQL Editor of your Supabase Dashboard

create table whitelist (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  fid bigint not null,
  username text
);

-- Enable Row Level Security (RLS)
alter table whitelist enable row level security;

-- Create a policy to allow anyone to insert (since it's a public mini app)
create policy "Enable insert for all users" on whitelist
  for insert with check (true);

-- Create a policy to allow reading (optional, if you want to show the list)
create policy "Enable read access for all users" on whitelist
  for select using (true);
